### ISSUE TITLE
Better model constructor for EnvelopeEvent and RecipientEvent

### ISSUE THREAD

**Issue by k0pernicus** [docusign/docusign-python-client#14]
Thanks for this great work!

Just a comment here:
is it possible to change the constructor parameters of `RecipientEvent`, to match with `EnvelopeEvent` please?

For example, the `RecipientEvent` object accepts first `include_documents`, and then `recipient_event_status_code`.
Otherwise, the parameters to instanciate an `EnvelopeSent` object are, first `recipient_event_status_code`, and then `include_documents`.

For me, as those objects correspond to the same logic, for a Recipient and for an Envelope, the parameters order should match (I spent maybe 10 minutes in solving a Rest API problem, just because I didn't care about the position of the parameters for `RecipientEvent`, as I used before the object `EnvelopeEvent`...).

**Comment by LarryKlugerDS** [comment]
Hi @k0pernicus,

First, please accept my apologies for this extremely delayed reply to your thoughtful issue. We have reorganized internally to provide faster responses to questions and suggestions.

Your idea for better consistency between the two objects is a good suggestion. Unfortunately, it would be a very low priority task for the DocuSign Engineering group.

I have a different suggestion for you to consider: instead of using positional arguments when creating the objects, use named arguments. That's how I've used the Python SDK in the large [eg-03-python-auth-code-grant](https://github.com/docusign/eg-03-python-auth-code-grant) example.

An example of this pattern:

````
    # Create the document models
    document1 = Document(  # create the DocuSign document object
        document_base64=doc1_b64,
        name='Order acknowledgement',  # can be different from actual file name
        file_extension='html',  # many different document types are accepted
        document_id='1'  # a label used to reference the doc
    )
````
Note that I'm using Python3, I'm not sure if it is available in Python2 or not.

Thanks,
Larry
