### ISSUE TITLE
Envelopes::listStatus method should call GET, not PUT

### ISSUE THREAD

**Issue by csirmazbendeguz** [docusign/docusign-python-client#77]
Hey!

I'm not sure where to report this. The Envelopes::listStatus method is not documented correctly:

https://developers.docusign.com/esign-rest-api/reference/Envelopes/Envelopes/listStatus
<img width="851" alt="Screenshot 2020-07-02 at 07 45 31" src="https://user-images.githubusercontent.com/19559023/86325508-0ff31200-bc38-11ea-8f95-27fbd0f3c5e5.png">

It should be GET, not PUT.
It's incorrect in the client too:

https://github.com/docusign/docusign-python-client/blob/master/docusign_esign/apis/envelopes_api.py#L8122

**Comment by LarryKlugerDS** [comment]
Hi! Sorry for the delay on this response. Do you mean that, from a RESTful design point of view, a status call should use `GET`, not `PUT`? Or something else?

Answer: `PUT` is used by design to enable an optional request body to be supplied. The request body can contain a list of `envelopeIds` for the query. If you want to specify the envelopeIds in the request body, set the query parameter `envelope_ids` to the special value `request_body`

`GET` calls can't include a request body.

Regards,
Larry

**Comment by csirmazbendeguz** [comment]
Hi, no, it was a bug report, it's not working with PUT, I'm getting the following error:

```
{"errorCode":"INVALID_REQUEST_BODY","message":"The request body is missing or improperly formatted."}
```

Anyway, I changed to using the `list_status_changes` method instead and it seems to work correctly.

**Comment by LarryKlugerDS** [comment]
Ahh, ok. I think the issue is that you need to include a null request body. This is a bug and I've filed bug report DCM-4409.
I'm glad that list_status_changes method is working for you.
